// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonsApp.Services;

namespace PersonsApp.Migrations
{
    [DbContext(typeof(PersonsAppDbContext))]
    [Migration("20220123152709_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonsApp.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = "6863c61a-0c57-4dd4-b813-f27e3e5327a9",
                            Email = "hmyrtle0@springer.com",
                            FirstName = "Hector",
                            LastName = "Myrtle",
                            PhoneNumber = "+964 (738) 110-9085"
                        },
                        new
                        {
                            Id = "fffbd69d-f767-4a5f-9ddf-da5dee2f40eb",
                            Email = "pjacquest1@elegantthemes.com",
                            FirstName = "Paton",
                            LastName = "Jacquest",
                            PhoneNumber = "+7 (651) 788-8216"
                        },
                        new
                        {
                            Id = "51136ebc-3c82-4132-912b-6747524b1913",
                            Email = "oinnwood2@dyndns.org",
                            FirstName = "Ofella",
                            LastName = "Innwood",
                            PhoneNumber = "+7 (697) 862-2582"
                        },
                        new
                        {
                            Id = "17cf0dbe-b17c-4034-ba93-29b5c31ec66a",
                            Email = "asimione3@bbb.org",
                            FirstName = "Antons",
                            LastName = "Simione",
                            PhoneNumber = "+84 (471) 662-4104"
                        },
                        new
                        {
                            Id = "77db017c-494c-4fae-9b55-8311cd6f4a47",
                            Email = "dospellissey4@house.gov",
                            FirstName = "Diane-marie",
                            LastName = "O'Spellissey",
                            PhoneNumber = "+62 (936) 753-8327"
                        },
                        new
                        {
                            Id = "8eaae67a-8e9f-4634-b9ec-c86d745bb5d9",
                            Email = "aissitt5@fema.gov",
                            FirstName = "Alec",
                            LastName = "Issitt",
                            PhoneNumber = "+358 (943) 239-7119"
                        },
                        new
                        {
                            Id = "973584f3-7a69-449f-aa10-c7a9a9c3e474",
                            Email = "bimpson6@odnoklassniki.ru",
                            FirstName = "Bethany",
                            LastName = "Impson",
                            PhoneNumber = "+260 (688) 624-0362"
                        },
                        new
                        {
                            Id = "f43f22d5-b9f7-4430-b429-0c827998bcdb",
                            Email = "mlawry7@wiley.com",
                            FirstName = "Mackenzie",
                            LastName = "Lawry",
                            PhoneNumber = "+86 (346) 365-6915"
                        },
                        new
                        {
                            Id = "264b9b35-072c-42a8-9ee3-c0f40317539d",
                            Email = "tbeverage8@intel.com",
                            FirstName = "Teodorico",
                            LastName = "Beverage",
                            PhoneNumber = "+385 (290) 328-6107"
                        },
                        new
                        {
                            Id = "4710cc77-52e1-4233-8135-f7fe7f785e21",
                            Email = "bsego9@mayoclinic.com",
                            FirstName = "Brynna",
                            LastName = "Sego",
                            PhoneNumber = "+380 (204) 212-6938"
                        },
                        new
                        {
                            Id = "6423a429-0df6-4e78-842c-8b2349e36ece",
                            Email = "mduckera@google.cn",
                            FirstName = "Morissa",
                            LastName = "Ducker",
                            PhoneNumber = "+63 (378) 486-4720"
                        },
                        new
                        {
                            Id = "e6ecbf3b-c8b4-4c98-81c0-062c108443dd",
                            Email = "cprestwichb@salon.com",
                            FirstName = "Chevy",
                            LastName = "Prestwich",
                            PhoneNumber = "+52 (464) 684-3846"
                        },
                        new
                        {
                            Id = "ad06ab12-79f4-4e17-a307-6e00a85ea910",
                            Email = "fburtonshawc@odnoklassniki.ru",
                            FirstName = "Fonsie",
                            LastName = "Burtonshaw",
                            PhoneNumber = "+86 (529) 821-1598"
                        },
                        new
                        {
                            Id = "075b96d1-b8aa-43f9-af95-8951ec0dd8da",
                            Email = "gaveralld@microsoft.com",
                            FirstName = "Gael",
                            LastName = "Averall",
                            PhoneNumber = "+93 (127) 414-8701"
                        },
                        new
                        {
                            Id = "8c1daae1-b2df-468b-b356-80992d0e34a4",
                            Email = "bcaltune@domainmarket.com",
                            FirstName = "Boycey",
                            LastName = "Caltun",
                            PhoneNumber = "+33 (510) 849-5352"
                        },
                        new
                        {
                            Id = "0f2db881-db1f-4c64-a744-826728854890",
                            Email = "cfaringtonf@npr.org",
                            FirstName = "Colas",
                            LastName = "Farington",
                            PhoneNumber = "+86 (935) 934-5208"
                        },
                        new
                        {
                            Id = "cfcc03e5-86c2-48db-894b-1f63f0feee8f",
                            Email = "xnestorg@prnewswire.com",
                            FirstName = "Ximenes",
                            LastName = "Nestor",
                            PhoneNumber = "+994 (793) 973-8882"
                        },
                        new
                        {
                            Id = "aebeea00-2744-405f-8911-e4445d0e74ab",
                            Email = "wstarth@mozilla.org",
                            FirstName = "Wayland",
                            LastName = "Start",
                            PhoneNumber = "+86 (680) 660-1536"
                        },
                        new
                        {
                            Id = "5939ac12-8a25-47d1-b2be-6f81027fdbc3",
                            Email = "gchantrelli@histats.com",
                            FirstName = "Geri",
                            LastName = "Chantrell",
                            PhoneNumber = "+507 (447) 916-1259"
                        },
                        new
                        {
                            Id = "5c11f1b6-4f64-4bf9-b0c1-7e24a77ccc9d",
                            Email = "ogarfitj@mapquest.com",
                            FirstName = "Osbert",
                            LastName = "Garfit",
                            PhoneNumber = "+86 (613) 836-4820"
                        },
                        new
                        {
                            Id = "64598115-9113-4856-b7b9-03e25627ff06",
                            Email = "wgallimorek@state.gov",
                            FirstName = "Wake",
                            LastName = "Gallimore",
                            PhoneNumber = "+255 (231) 806-3338"
                        },
                        new
                        {
                            Id = "9eaee2f2-c0f6-47e7-aa41-9a808d6f7fcc",
                            Email = "rfilippellol@vimeo.com",
                            FirstName = "Ryun",
                            LastName = "Filippello",
                            PhoneNumber = "+351 (514) 492-6694"
                        },
                        new
                        {
                            Id = "c2db0879-f68d-4618-9539-9bcbb062396d",
                            Email = "tkollachm@liveinternet.ru",
                            FirstName = "Tansy",
                            LastName = "Kollach",
                            PhoneNumber = "+380 (873) 410-8916"
                        },
                        new
                        {
                            Id = "066badc0-b5c7-4b07-b17d-3db194a81f2e",
                            Email = "grashleighn@vkontakte.ru",
                            FirstName = "Gradeigh",
                            LastName = "Rashleigh",
                            PhoneNumber = "+86 (292) 860-8464"
                        },
                        new
                        {
                            Id = "866e0cdc-e726-46a6-9fd1-31fbf17f07e2",
                            Email = "edabinetto@webnode.com",
                            FirstName = "Elfrieda",
                            LastName = "Dabinett",
                            PhoneNumber = "+62 (806) 678-0983"
                        },
                        new
                        {
                            Id = "30d214c5-f75e-426d-b500-2043065cf506",
                            Email = "adomonkosp@nba.com",
                            FirstName = "Adele",
                            LastName = "Domonkos",
                            PhoneNumber = "+62 (876) 203-5983"
                        },
                        new
                        {
                            Id = "e1ea14b8-ba75-4ff3-a2c0-69ed0a59a0ba",
                            Email = "mmcellenq@1688.com",
                            FirstName = "Mattie",
                            LastName = "McEllen",
                            PhoneNumber = "+216 (860) 160-3252"
                        },
                        new
                        {
                            Id = "e135cabe-aec8-4927-8a5f-79cefe95c62c",
                            Email = "epennellsr@bandcamp.com",
                            FirstName = "Emili",
                            LastName = "Pennells",
                            PhoneNumber = "+49 (851) 358-3477"
                        },
                        new
                        {
                            Id = "7321e91f-4aa5-44cf-ae43-e0433d5a7580",
                            Email = "chatchetts@mit.edu",
                            FirstName = "Cher",
                            LastName = "Hatchett",
                            PhoneNumber = "+86 (605) 426-2601"
                        },
                        new
                        {
                            Id = "9348cba6-ab84-45d4-9a8c-80c3a68f433e",
                            Email = "rpeschmannt@twitpic.com",
                            FirstName = "Rich",
                            LastName = "Peschmann",
                            PhoneNumber = "+7 (402) 317-1264"
                        },
                        new
                        {
                            Id = "2d2a96b4-2c32-4bf0-9a89-938d45cda0c7",
                            Email = "abrownlowu@springer.com",
                            FirstName = "Amos",
                            LastName = "Brownlow",
                            PhoneNumber = "+86 (321) 276-4173"
                        },
                        new
                        {
                            Id = "aaaf421c-f8a9-4705-97ee-aa3ce959be08",
                            Email = "ydennehyv@fastcompany.com",
                            FirstName = "Yankee",
                            LastName = "Dennehy",
                            PhoneNumber = "+53 (889) 146-1075"
                        },
                        new
                        {
                            Id = "d6c61a90-1807-4156-b529-37852f34d93d",
                            Email = "ljaneczekw@bravesites.com",
                            FirstName = "Leonerd",
                            LastName = "Janeczek",
                            PhoneNumber = "+1 (510) 728-9713"
                        },
                        new
                        {
                            Id = "16365679-c259-4dd2-b68d-9e9be1ce9981",
                            Email = "lbretlandx@buzzfeed.com",
                            FirstName = "Liuka",
                            LastName = "Bretland",
                            PhoneNumber = "+63 (533) 659-3832"
                        },
                        new
                        {
                            Id = "e2799bc3-aabf-4791-b732-d119b78945f6",
                            Email = "ecanketty@umich.edu",
                            FirstName = "Elissa",
                            LastName = "Cankett",
                            PhoneNumber = "+54 (371) 981-2267"
                        },
                        new
                        {
                            Id = "94bf3198-7ad6-4e10-853e-bf7c9de69115",
                            Email = "eparrz@chicagotribune.com",
                            FirstName = "Egon",
                            LastName = "Parr",
                            PhoneNumber = "+33 (137) 613-3518"
                        },
                        new
                        {
                            Id = "a43b905a-5c42-4333-bff9-095f841c12af",
                            Email = "swestoll10@buzzfeed.com",
                            FirstName = "Sadella",
                            LastName = "Westoll",
                            PhoneNumber = "+86 (907) 440-1802"
                        },
                        new
                        {
                            Id = "38cb3dcd-6a9a-42d1-89b2-a0be07c53bad",
                            Email = "ijeffrey11@utexas.edu",
                            FirstName = "Ina",
                            LastName = "Jeffrey",
                            PhoneNumber = "+27 (338) 369-1467"
                        },
                        new
                        {
                            Id = "5f4ccab3-1e0d-47a9-a059-e62f4577f026",
                            Email = "pswanwick12@sciencedirect.com",
                            FirstName = "Paton",
                            LastName = "Swanwick",
                            PhoneNumber = "+86 (928) 400-3191"
                        },
                        new
                        {
                            Id = "7b3f3320-fa87-4429-aeb3-f87580103531",
                            Email = "rmoroney13@wikimedia.org",
                            FirstName = "Rochette",
                            LastName = "Moroney",
                            PhoneNumber = "+55 (787) 595-5674"
                        },
                        new
                        {
                            Id = "db5b385c-3fba-490f-961c-392fe4fde1fb",
                            Email = "ekuschel14@creativecommons.org",
                            FirstName = "Elroy",
                            LastName = "Kuschel",
                            PhoneNumber = "+256 (954) 448-1313"
                        },
                        new
                        {
                            Id = "a40e7edf-3622-452f-8b18-a3999b708e77",
                            Email = "hwillerstone15@dell.com",
                            FirstName = "Huey",
                            LastName = "Willerstone",
                            PhoneNumber = "+236 (133) 475-3999"
                        },
                        new
                        {
                            Id = "24b40736-3050-475c-be22-71775adb9335",
                            Email = "gcrann16@utexas.edu",
                            FirstName = "Georges",
                            LastName = "Crann",
                            PhoneNumber = "+63 (755) 314-1318"
                        },
                        new
                        {
                            Id = "b1e6ae6d-a37a-45d8-a5e7-493e6585967b",
                            Email = "ebenezet17@rediff.com",
                            FirstName = "Elia",
                            LastName = "Benezet",
                            PhoneNumber = "+86 (841) 901-4065"
                        },
                        new
                        {
                            Id = "4e6ea553-c0db-4316-a399-e7a73927d3e8",
                            Email = "mnewcome18@amazon.co.jp",
                            FirstName = "Melisent",
                            LastName = "Newcome",
                            PhoneNumber = "+381 (136) 118-4504"
                        },
                        new
                        {
                            Id = "53b8df0b-e1e4-4f05-9807-6b3257dd254c",
                            Email = "ftudge19@statcounter.com",
                            FirstName = "Florence",
                            LastName = "Tudge",
                            PhoneNumber = "+1 (209) 194-0052"
                        },
                        new
                        {
                            Id = "f7c45640-4c8d-4733-a2c3-4ed620a91fc8",
                            Email = "lsieghart1a@t-online.de",
                            FirstName = "Lief",
                            LastName = "Sieghart",
                            PhoneNumber = "+62 (435) 425-5549"
                        },
                        new
                        {
                            Id = "e90c185e-a903-4ea0-82bf-345fd7f0451d",
                            Email = "lpheasant1b@dyndns.org",
                            FirstName = "Ludovika",
                            LastName = "Pheasant",
                            PhoneNumber = "+420 (640) 787-3073"
                        },
                        new
                        {
                            Id = "86e5c52f-6297-4202-bb93-a108c2b33466",
                            Email = "dllop1c@dell.com",
                            FirstName = "Deni",
                            LastName = "Llop",
                            PhoneNumber = "+62 (576) 342-4462"
                        },
                        new
                        {
                            Id = "74f3eff5-8a09-4497-b589-8f819d2524bf",
                            Email = "gferretti1d@prweb.com",
                            FirstName = "Gareth",
                            LastName = "Ferretti",
                            PhoneNumber = "+55 (185) 381-9198"
                        },
                        new
                        {
                            Id = "9957a911-1c51-42b8-b685-82199a21bcab",
                            Email = "kjuzek1e@usgs.gov",
                            FirstName = "Kerr",
                            LastName = "Juzek",
                            PhoneNumber = "+81 (104) 870-3109"
                        },
                        new
                        {
                            Id = "c33214c1-d6fb-463b-95c0-280e0b281203",
                            Email = "mpetrik1f@flickr.com",
                            FirstName = "Marita",
                            LastName = "Petrik",
                            PhoneNumber = "+1 (303) 534-2167"
                        },
                        new
                        {
                            Id = "9f919acc-1105-44ac-ae16-c11e32f591b0",
                            Email = "bmccalister1g@buzzfeed.com",
                            FirstName = "Byran",
                            LastName = "McCalister",
                            PhoneNumber = "+86 (935) 815-6309"
                        },
                        new
                        {
                            Id = "51b37de1-880d-4fae-a094-ac22f85a2bf4",
                            Email = "iverity1h@yahoo.co.jp",
                            FirstName = "Imogen",
                            LastName = "Verity",
                            PhoneNumber = "+351 (437) 849-8092"
                        },
                        new
                        {
                            Id = "08d601f0-beae-4147-80fe-a6da224f879d",
                            Email = "yraffon1i@china.com.cn",
                            FirstName = "Yanaton",
                            LastName = "Raffon",
                            PhoneNumber = "+7 (756) 791-2582"
                        },
                        new
                        {
                            Id = "3d19753a-a607-46c7-be3c-c4864c3263d0",
                            Email = "rdann1j@devhub.com",
                            FirstName = "Reynard",
                            LastName = "Dann",
                            PhoneNumber = "+385 (361) 305-7283"
                        },
                        new
                        {
                            Id = "a6d9e749-12fa-4252-b3db-835c8a2b99b9",
                            Email = "akordovani1k@bravesites.com",
                            FirstName = "Ailsun",
                            LastName = "Kordovani",
                            PhoneNumber = "+58 (643) 604-2006"
                        },
                        new
                        {
                            Id = "e643bfb8-0c85-4535-9a60-ed710f6ca65d",
                            Email = "acrocket1l@addthis.com",
                            FirstName = "Abie",
                            LastName = "Crocket",
                            PhoneNumber = "+62 (159) 723-7659"
                        },
                        new
                        {
                            Id = "76da52c2-0e2b-42a8-bbec-0c14ab403306",
                            Email = "vstrephan1m@scientificamerican.com",
                            FirstName = "Vonnie",
                            LastName = "Strephan",
                            PhoneNumber = "+48 (881) 196-1993"
                        },
                        new
                        {
                            Id = "e09ae8fb-19f8-4cfe-90a4-a41ee9fdf177",
                            Email = "rbowden1n@google.nl",
                            FirstName = "Ronnie",
                            LastName = "Bowden",
                            PhoneNumber = "+216 (767) 111-9990"
                        },
                        new
                        {
                            Id = "24a81392-b6cf-45b0-a397-3c098f22a451",
                            Email = "ptreasure1o@homestead.com",
                            FirstName = "Pooh",
                            LastName = "Treasure",
                            PhoneNumber = "+86 (892) 587-3845"
                        },
                        new
                        {
                            Id = "adb098c0-e9c3-429a-a084-6290ef9611f4",
                            Email = "gpoltone1p@php.net",
                            FirstName = "Gilligan",
                            LastName = "Poltone",
                            PhoneNumber = "+81 (430) 600-9966"
                        },
                        new
                        {
                            Id = "ffcd7bfb-be72-45f5-816d-2d466a1e4dbf",
                            Email = "jchiplin1q@eepurl.com",
                            FirstName = "Jory",
                            LastName = "Chiplin",
                            PhoneNumber = "+353 (808) 967-9884"
                        },
                        new
                        {
                            Id = "9dea7f61-de77-4708-92d2-fece80666344",
                            Email = "sjeens1r@psu.edu",
                            FirstName = "Sisile",
                            LastName = "Jeens",
                            PhoneNumber = "+63 (174) 181-4840"
                        },
                        new
                        {
                            Id = "bef25000-ca93-4a43-bfe0-637172cf0add",
                            Email = "eburel1s@symantec.com",
                            FirstName = "Eadmund",
                            LastName = "Burel",
                            PhoneNumber = "+351 (845) 728-5543"
                        },
                        new
                        {
                            Id = "2ecf331e-7522-4c37-8b40-011555e9a2eb",
                            Email = "pshoosmith1t@dmoz.org",
                            FirstName = "Pavla",
                            LastName = "Shoosmith",
                            PhoneNumber = "+62 (964) 467-9441"
                        },
                        new
                        {
                            Id = "f9bffeaa-c972-44ee-b5b8-f78bfba71937",
                            Email = "bgartell1u@amazon.com",
                            FirstName = "Benjamen",
                            LastName = "Gartell",
                            PhoneNumber = "+86 (442) 645-7437"
                        },
                        new
                        {
                            Id = "193a82fe-0e49-4261-95dd-59fd894339ed",
                            Email = "omccromley1v@tmall.com",
                            FirstName = "Orton",
                            LastName = "McCromley",
                            PhoneNumber = "+53 (575) 506-6579"
                        },
                        new
                        {
                            Id = "e43c7ed7-917b-4342-8208-79dc34e019c6",
                            Email = "wwaite1w@sina.com.cn",
                            FirstName = "Weber",
                            LastName = "Waite",
                            PhoneNumber = "+255 (892) 586-3521"
                        },
                        new
                        {
                            Id = "f02a487a-6e76-465d-90b3-86397563bec8",
                            Email = "skaasmann1x@deviantart.com",
                            FirstName = "Sheilah",
                            LastName = "Kaasmann",
                            PhoneNumber = "+44 (109) 493-6965"
                        },
                        new
                        {
                            Id = "d908bafc-57cb-40e0-ae7e-0651e55c8fe8",
                            Email = "rdreghorn1y@bandcamp.com",
                            FirstName = "Rafaellle",
                            LastName = "Dreghorn",
                            PhoneNumber = "+57 (607) 907-7268"
                        },
                        new
                        {
                            Id = "1e97768b-2bfc-4f68-b859-8c0a02e34874",
                            Email = "hleisk1z@youku.com",
                            FirstName = "Hamid",
                            LastName = "Leisk",
                            PhoneNumber = "+353 (583) 414-7372"
                        },
                        new
                        {
                            Id = "2fbc37fb-2946-41d6-b3a7-91a27c41abf9",
                            Email = "galleway20@dyndns.org",
                            FirstName = "Gilburt",
                            LastName = "Alleway",
                            PhoneNumber = "+383 (689) 367-3640"
                        },
                        new
                        {
                            Id = "544f3b86-5cf9-4d36-8a81-662d744d6d4c",
                            Email = "ebristow21@google.nl",
                            FirstName = "Elva",
                            LastName = "Bristow",
                            PhoneNumber = "+57 (125) 324-7261"
                        },
                        new
                        {
                            Id = "fbde0509-112b-41e8-a259-877caf356119",
                            Email = "eegginson22@chron.com",
                            FirstName = "Eleanora",
                            LastName = "Egginson",
                            PhoneNumber = "+420 (998) 524-2206"
                        },
                        new
                        {
                            Id = "d85f94f7-599a-4a0f-8c07-e9d5e70f152c",
                            Email = "rblackleech23@jigsy.com",
                            FirstName = "Roddie",
                            LastName = "Blackleech",
                            PhoneNumber = "+48 (306) 208-9819"
                        },
                        new
                        {
                            Id = "21eff3f1-590f-41db-8fca-41699099e400",
                            Email = "kbage24@mtv.com",
                            FirstName = "Kacy",
                            LastName = "Bage",
                            PhoneNumber = "+55 (481) 567-6976"
                        },
                        new
                        {
                            Id = "02ffca6c-506f-4eec-a62c-a13579a478dc",
                            Email = "slowth25@house.gov",
                            FirstName = "Sherwood",
                            LastName = "Lowth",
                            PhoneNumber = "+55 (173) 445-6267"
                        },
                        new
                        {
                            Id = "537b57e7-ab3c-42be-8f47-d614cebd6190",
                            Email = "wmulhill26@newyorker.com",
                            FirstName = "Winny",
                            LastName = "Mulhill",
                            PhoneNumber = "+374 (479) 751-7770"
                        },
                        new
                        {
                            Id = "b2429c85-da84-4a87-a18b-87715289f962",
                            Email = "lsurfleet27@facebook.com",
                            FirstName = "Lyndsie",
                            LastName = "Surfleet",
                            PhoneNumber = "+46 (853) 673-9058"
                        },
                        new
                        {
                            Id = "019af437-1a43-4b42-8061-d9cca6b02fce",
                            Email = "ccollingworth28@surveymonkey.com",
                            FirstName = "Carlin",
                            LastName = "Collingworth",
                            PhoneNumber = "+880 (196) 574-6706"
                        },
                        new
                        {
                            Id = "367bd04b-8e42-4bfa-82b2-7bf0b0373685",
                            Email = "fhurt29@prweb.com",
                            FirstName = "Freemon",
                            LastName = "Hurt",
                            PhoneNumber = "+968 (693) 924-0149"
                        },
                        new
                        {
                            Id = "d4adc7be-3634-4473-b5d4-3eaadccf1021",
                            Email = "stitcomb2a@nymag.com",
                            FirstName = "Seymour",
                            LastName = "Titcomb",
                            PhoneNumber = "+62 (820) 410-3475"
                        },
                        new
                        {
                            Id = "3780f4d5-66da-406a-bb00-1f9c9003d825",
                            Email = "kofairy2b@scientificamerican.com",
                            FirstName = "Kinnie",
                            LastName = "O'Fairy",
                            PhoneNumber = "+48 (130) 680-1283"
                        },
                        new
                        {
                            Id = "08fa2c5e-5487-457e-bace-ebd22f35bead",
                            Email = "starrier2c@microsoft.com",
                            FirstName = "Shirlene",
                            LastName = "Tarrier",
                            PhoneNumber = "+86 (255) 963-9940"
                        },
                        new
                        {
                            Id = "1c9ab596-c0c7-4d49-9a6e-bf54490544a2",
                            Email = "dpyatt2d@utexas.edu",
                            FirstName = "Dianne",
                            LastName = "Pyatt",
                            PhoneNumber = "+48 (615) 447-3607"
                        },
                        new
                        {
                            Id = "18f20c39-c1e6-4d8f-8d9b-0c2f5ffa3acc",
                            Email = "aalbon2e@artisteer.com",
                            FirstName = "Allene",
                            LastName = "Albon",
                            PhoneNumber = "+57 (553) 555-7079"
                        },
                        new
                        {
                            Id = "78d98ab7-49d8-44aa-bd88-e4753b8da56b",
                            Email = "apattinson2f@technorati.com",
                            FirstName = "Alexandro",
                            LastName = "Pattinson",
                            PhoneNumber = "+7 (864) 620-0780"
                        },
                        new
                        {
                            Id = "63340fd3-950c-4b30-8820-79e2e0853739",
                            Email = "mmerrill2g@friendfeed.com",
                            FirstName = "Margy",
                            LastName = "Merrill",
                            PhoneNumber = "+62 (987) 287-6628"
                        },
                        new
                        {
                            Id = "e1d6fd5f-8373-40af-991e-024441dde1a8",
                            Email = "ltesauro2h@vinaora.com",
                            FirstName = "Lorinda",
                            LastName = "Tesauro",
                            PhoneNumber = "+7 (289) 190-9417"
                        },
                        new
                        {
                            Id = "d63fe64e-fb82-45a6-a304-5e1fdc865e53",
                            Email = "fphethean2i@yahoo.com",
                            FirstName = "Felizio",
                            LastName = "Phethean",
                            PhoneNumber = "+62 (578) 908-4011"
                        },
                        new
                        {
                            Id = "06a91a98-8306-42fb-9a55-2031fe96198f",
                            Email = "ohinchshaw2j@jalbum.net",
                            FirstName = "Odell",
                            LastName = "Hinchshaw",
                            PhoneNumber = "+55 (865) 152-9130"
                        },
                        new
                        {
                            Id = "c162e507-3089-422f-afa3-b7d1e97e4106",
                            Email = "jslewcock2k@apple.com",
                            FirstName = "Jabez",
                            LastName = "Slewcock",
                            PhoneNumber = "+358 (234) 997-4698"
                        },
                        new
                        {
                            Id = "9e9da6d3-5a53-4100-ab77-18c54b876346",
                            Email = "mdunleavy2l@last.fm",
                            FirstName = "Mischa",
                            LastName = "Dunleavy",
                            PhoneNumber = "+972 (554) 251-5292"
                        },
                        new
                        {
                            Id = "a255ff6c-438c-4921-9ed2-dcafee2e9780",
                            Email = "theathcoat2m@squarespace.com",
                            FirstName = "Tish",
                            LastName = "Heathcoat",
                            PhoneNumber = "+33 (633) 597-1473"
                        },
                        new
                        {
                            Id = "3921675a-8f68-4709-9933-4ee1a4d3b3e1",
                            Email = "mmckag2n@posterous.com",
                            FirstName = "Massimo",
                            LastName = "McKag",
                            PhoneNumber = "+976 (822) 655-5507"
                        },
                        new
                        {
                            Id = "feb938c1-e1b9-4032-8f44-7c3f5c9a1c72",
                            Email = "tdorrance2o@mediafire.com",
                            FirstName = "Teodoro",
                            LastName = "Dorrance",
                            PhoneNumber = "+58 (136) 369-5101"
                        },
                        new
                        {
                            Id = "d7ec66dd-101c-4561-8969-de95b81bba1a",
                            Email = "cpalek2p@netscape.com",
                            FirstName = "Camala",
                            LastName = "Palek",
                            PhoneNumber = "+81 (246) 767-2230"
                        },
                        new
                        {
                            Id = "e72b8704-52da-4644-87af-505b2e3eb54c",
                            Email = "sdcosta2q@unblog.fr",
                            FirstName = "Susette",
                            LastName = "D'Costa",
                            PhoneNumber = "+30 (708) 144-0109"
                        },
                        new
                        {
                            Id = "f005d846-7dc7-4fe7-9f0b-f562aceffbeb",
                            Email = "wjantzen2r@comcast.net",
                            FirstName = "Wilfrid",
                            LastName = "Jantzen",
                            PhoneNumber = "+33 (655) 167-2764"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
